use_frameworks!
platform :ios, '10.0'

target 'DigiMeSDKExample' do
  pod 'DigiMeSDK', :path => '../'
  
  target 'DigiMeSDKExample_Tests' do
    inherit! :complete
    
    ####### SPECTA ######
    pod 'Specta',       '~> 1.0'
    pod 'Expecta',      '~> 1.0'   # expecta matchers
    pod 'OHHTTPStubs/Swift'
    #####################
    
  end
end
