use_frameworks!
platform :ios, '10.0'

target 'DigiMeSDKExample' do
  pod 'DigiMeSDK', :path => '../'
  pod 'DigiMeSDK/GuestConsent', :path => '../'
  pod 'DigiMeSDK/Postbox', :path => '../'
  
  target 'DigiMeSDKExample_Tests' do
    inherit! :search_paths

    
  end
end
