use_frameworks!
platform :ios, '11.0'

target 'DigiMeSDKExample' do
  pod 'DigiMeSDK', :path => '../'
  pod 'SwiftJWT'

  target 'DigiMeSDKExample_Tests' do
    inherit! :complete
    
    pod 'OHHTTPStubs/Swift'
    
  end
end
