use_frameworks!
platform :ios, '11.0'

target 'DigiMeSDKExample' do
  pod 'DigiMeSDK', :path => '../../'
end

target 'DigiMeSDKExample_Tests' do
    inherit! :search_paths
   
   	pod 'DigiMeSDK', :path => '../../' 
    pod 'OHHTTPStubs/Swift'
    
end
