# Rules list as of pod version 0.28.1

included:
  - DigiMeRepository
  - ../DigiMeRepository
  - ../DigiMeRepository/Objects
  - ../DigiMeRepository/Objects/Financial
  - ../DigiMeRepository/Accounts

disabled_rules: # rule identifiers to exclude from running
#  - block_based_kvo
#  - class_delegate_protocol
#  - closing_brace
#  - closure_parameter_position
#  - colon
#  - comma
#  - compiler_protocol_init
#  - control_statement
#  - custom_rules
#  - cyclomatic_complexity
#  - discarded_notification_center_observer
#  - discouraged_direct_init
#  - dynamic_inline
#  - empty_enum_arguments
#  - empty_parameters
#  - empty_parentheses_with_trailing_closure
#  - file_length
#  - for_where
  - force_cast # re-disable
#  - force_try
  - function_body_length
#  - function_parameter_count
#  - generic_type_name
  - identifier_name
#  - implicit_getter
#  - inert_defer
#  - is_disjoint
#  - large_tuple
#  - leading_whitespace
#  - legacy_cggeometry_functions
#  - legacy_constant
#  - legacy_constructor
#  - legacy_nsgeometry_functions
  - line_length
#  - mark
#  - multiple_closures_with_trailing_closure
#  - nesting
#  - no_fallthrough_only
#  - notification_center_detachment
#  - opening_brace
#  - operator_whitespace
  - private_over_fileprivate
#  - private_unit_test
#  - protocol_property_accessors_order
#  - redundant_discardable_let
#  - redundant_optional_initialization
#  - redundant_set_access_control
#  - redundant_string_enum_value
#  - redundant_void_return
#  - return_arrow_whitespace
#  - shorthand_operator
#  - statement_position
#  - superfluous_disable_command
#  - switch_case_alignment
#  - syntactic_sugar
  - todo
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
  - type_body_length
#  - type_name
#  - unneeded_break_in_switch
#  - unused_closure_parameter
#  - unused_enumerated
#  - unused_optional_binding
#  - valid_ibinspectable
#  - vertical_parameter_alignment
#  - vertical_whitespace
#  - void_return
#  - weak_delegate
#  - xctfail_message

opt_in_rules:
  - anyobject_protocol
  - array_init
#  - attributes
#  - closure_body_length # requires Swift 4.2
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
#  - discouraged_optional_boolean
#  - discouraged_optional_collection
#  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
#  - explicit_acl
#  - explicit_enum_raw_value
  - explicit_init
#  - explicit_top_level_acl
#  - explicit_type_interface
#  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
#  - file_name # disable for now, though is useful as ensures that file name reflects at least one of the types/extensions in file
  - first_where
  - function_default_parameter_at_end
#  - force_unwrapping
  - identical_operands
  - implicit_return
#  - implicitly_unwrapped_optional // Re-enable
  - joined_default_parameter
  - legacy_random
#  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
#  - multiline_function_chains
  - multiline_parameters
#  - nimble_operator
#  - no_extension_access_modifier
#  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
#  - quick_discouraged_call
#  - quick_discouraged_focused_test
#  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
#  - strict_fileprivate
  - switch_case_on_newline
#  - toggle_bool # requires Swift 4.2
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
#  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

cyclomatic_complexity:
  warning: 15
  error: 30

file_header:
  required_pattern: |
                    \/\/
                    \/\/  SWIFTLINT_CURRENT_FILENAME
                    \/\/  \DigiMeRepository\
                    \/\/
                    \/\/  Created on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4}(\s?-\s?\d{4})? digi\.me Limited?\. All rights reserved\.
                    \/\/

empty_count:
  severity: warning
#
#explicit_type_interface:
#  allow_redundancy: false

file_length:
  warning: 1000
  error: 2000

#file_name:
#  prefix_pattern:
#  suffix_pattern:

force_cast:
  severity: warning

identifier_name:
  severity: warning

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

number_separator:
  minimum_length: 5
  minimum_fraction_length: 8

object_literal:
  image_literal: false

shorthand_operator:
  severity: warning

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_empty_lines: true

#identifier_name:
#  excluded:
#    - id
#  validates_start_with_lowercase: false

  

