use_frameworks!
platform :ios, '10.0'

target 'DigiMeRepository_Example' do
  pod 'DigiMeSDK/Repository', :path => '../../'
  pod 'SwiftLint'

  target 'DigiMeRepository_Tests' do
    inherit! :search_paths
  end
end
