use_frameworks!
use_modular_headers!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'DigiMeSDKExample' do
  pod 'DigiMeSDK'
  pod 'SwiftLint'

  target 'DigiMeSDKExampleTests' do
    inherit! :search_paths
  end
end
