platform :ios, '13.0'

install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true

use_frameworks!
use_modular_headers!

source 'https://cdn.cocoapods.org/'

target 'Genrefy' do
    pod 'DigiMeSDK', :path => '../../'
    pod 'SwiftLint'
end
